name: Testes Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Rodar Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  

      - name: Instalar dependências
        run: go mod download

      - name: Rodar testes com cobertura
        run: go test -coverprofile=coverage.out ./...

      - name: Mostrar cobertura no terminal
        run: go tool cover -func=coverage.out

      - name: Upload da cobertura como artefato
        uses: actions/upload-artifact@v4
        with:
          name: cobertura
          path: coverage.out
